### ISSUE TITLE
Progress reporting parent Issue

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#1036]
Progress reporting task list:
- [x] Namespaces drill down view. #1037 
- [x] Migrations drill down view. #1038 
- [x] Migration details drill down view. 
- [x] Migration details child step drill down view.

**Comment by pranavgaikwad** [comment]
@ibolton336 I think this can be closed now
