### ISSUE TITLE
Non-admin feature tracker

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#882]
Tracking issue for non-admin work issues and general discussion:

- [ ] [Determine multi-tenant vs. single-tenant non-admin design](#)
- [ ] [UI needs to be made aware if in admin vs. non-admin mode](#)
- [ ] [Implement tokens screen ](#)
- [ ] [Implement regenerate OAuth token](#)
- [ ] [Implement welcome screen](#)
- [ ] [Implement expired token modal](#)
- [ ] [Implement MigPlan general step](#)
- [ ] [Implement token edit](#)
- [ ] [Add MigToken support to k8s client](#)
- [ ] [Implement add token for Cluster](#)
- [ ] [Implement cluster status ](#)
- [ ] [Automatically add MigToken with host logged-in user OAuth token](#)
- [ ] [Implement host MigToken OAuth update on login](#)
- [ ] [List of clusters should be sourced from discovery service](#)
- [ ] [Implement empty state view for clusters w/ non-admin](#)

**Comment by eriknelson** [comment]
https://github.com/konveyor/mig-ui/issues/883 needs to be closed ASAP as that decision will dictate a lot of the implementation details.
